[project]
name = "nioflux"
version = "0.0.1.alpha"
description = "A lightweight asynchronous scalable TCP frame protocol server."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "vortezwohl>=0.0.10",
]
